###
http://localhost:3000/api

###
POST http://localhost:3000/api/pets
Content-Type: application/json
{
  "category":"犬",
  "name":"りん",
  "photoUrls":"",
  "tags":"",
  "status":"健康"
}

###
GET http://localhost:3000/api/pets?status=available